### ISSUE TITLE
missing function in core.py

### ISSUE THREAD

**Issue by Youmna-Salah** [BatsResearch/nayak-arxiv20-code#6]
Hello!

I was running the code while adapting it for another dataset then I ran into an error from the 'core.convert_index_to_int' function called [here](https://github.com/BatsResearch/nayak-arxiv20-code/blob/d7eced950ba1406d06c47bb664fcc01d6db7cf5c/graph_utils/random_walk.py#L71). I didn't find such a function in the core.py file, could you pls provide us with a pointer to the 'convert_index_to_int' function's implementation?

**Comment by nihalnayak** [comment]
Hi @Youmna-Salah! Thank you for reporting this bug. I think these issues are due to a mixing of old and new code. I will resolve this issue later this week.

Meanwhile, after running the `query_conceptnet()` function in `main.py`, you could follow the tutorial on [setting up knowledge graphs](https://github.com/BatsResearch/zsl-kg/blob/master/tutorials/knowledge_graph/knowledge_graph.ipynb) to compute the hitting probabilities on your knowledge graph.

**Comment by nihalnayak** [comment]
hi @Youmna-Salah 

I have updated the code to query the graph. Please reach out if you face any issues. 

https://github.com/BatsResearch/nayak-arxiv20-code/tree/master/graph_utils
